In [24]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import Imputer
from IPython.display import display, HTML

In [25]:
datos = pd.read_csv('On_Time_On_Time_Performance_2015_1.csv') #cargamos archivo

/usr/local/bin/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (77,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [26]:
print("Número de renglones:" + str(len(datos))) #displeyamos el número de registros

Número de renglones:469968

In [27]:
datos.head(10) #imprimimos los 10 primeros registros

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,UniqueCarrier,AirlineID,Carrier,TailNum,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2015,1,1,1,4,2015-01-01,AA,19805,AA,N787AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,2,5,2015-01-02,AA,19805,AA,N795AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,3,6,2015-01-03,AA,19805,AA,N788AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,7,2015-01-04,AA,19805,AA,N791AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,5,1,2015-01-05,AA,19805,AA,N783AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,6,2,2015-01-06,AA,19805,AA,N799AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,7,3,2015-01-07,AA,19805,AA,N784AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,8,4,2015-01-08,AA,19805,AA,N787AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,9,5,2015-01-09,AA,19805,AA,N795AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,10,6,2015-01-10,AA,19805,AA,N790AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
datos.head(0) #imprimimos el nombre de las columnas

Empty DataFrame
Columns: [Year, Quarter, Month, DayofMonth, DayOfWeek, FlightDate, UniqueCarrier, AirlineID, Carrier, TailNum, FlightNum, OriginAirportID, OriginAirportSeqID, OriginCityMarketID, Origin, OriginCityName, OriginState, OriginStateFips, OriginStateName, OriginWac, DestAirportID, DestAirportSeqID, DestCityMarketID, Dest, DestCityName, DestState, DestStateFips, DestStateName, DestWac, CRSDepTime, DepTime, DepDelay, DepDelayMinutes, DepDel15, DepartureDelayGroups, DepTimeBlk, TaxiOut, WheelsOff, WheelsOn, TaxiIn, CRSArrTime, ArrTime, ArrDelay, ArrDelayMinutes, ArrDel15, ArrivalDelayGroups, ArrTimeBlk, Cancelled, CancellationCode, Diverted, CRSElapsedTime, ActualElapsedTime, AirTime, Flights, Distance, DistanceGroup, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay, FirstDepTime, TotalAddGTime, LongestAddGTime, DivAirportLandings, DivReachedDest, DivActualElapsedTime, DivArrDelay, DivDistance, Div1Airport, Div1AirportID, Div1AirportSeqID, Div1WheelsOn, Div1TotalGTime, Div1LongestGTime, Div1WheelsOff, Div1TailNum, Div2Airport, Div2AirportID, Div2AirportSeqID, Div2WheelsOn, Div2TotalGTime, Div2LongestGTime, Div2WheelsOff, Div2TailNum, Div3Airport, Div3AirportID, Div3AirportSeqID, Div3WheelsOn, Div3TotalGTime, Div3LongestGTime, Div3WheelsOff, Div3TailNum, Div4Airport, Div4AirportID, Div4AirportSeqID, Div4WheelsOn, Div4TotalGTime, Div4LongestGTime, Div4WheelsOff, ...]
Index: []

[0 rows x 110 columns]

In [29]:
datos.dtypes #imprimimos el tipo de dato de cada columna

Year                    int64
Quarter                 int64
Month                   int64
DayofMonth              int64
DayOfWeek               int64
FlightDate             object
UniqueCarrier          object
AirlineID               int64
Carrier                object
TailNum                object
FlightNum               int64
OriginAirportID         int64
OriginAirportSeqID      int64
OriginCityMarketID      int64
Origin                 object
OriginCityName         object
OriginState            object
OriginStateFips         int64
OriginStateName        object
OriginWac               int64
DestAirportID           int64
DestAirportSeqID        int64
DestCityMarketID        int64
Dest                   object
DestCityName           object
DestState              object
DestStateFips           int64
DestStateName          object
DestWac                 int64
CRSDepTime              int64
                       ...
Div2WheelsOn          float64
Div2TotalGTime        float64
Div2LongestGTime      float64
Div2WheelsOff         float64
Div2TailNum            object
Div3Airport            object
Div3AirportID         float64
Div3AirportSeqID      float64
Div3WheelsOn          float64
Div3TotalGTime        float64
Div3LongestGTime      float64
Div3WheelsOff         float64
Div3TailNum           float64
Div4Airport           float64
Div4AirportID         float64
Div4AirportSeqID      float64
Div4WheelsOn          float64
Div4TotalGTime        float64
Div4LongestGTime      float64
Div4WheelsOff         float64
Div4TailNum           float64
Div5Airport           float64
Div5AirportID         float64
Div5AirportSeqID      float64
Div5WheelsOn          float64
Div5TotalGTime        float64
Div5LongestGTime      float64
Div5WheelsOff         float64
Div5TailNum           float64
Unnamed: 109          float64
dtype: object

In [30]:
#para detecar el

In [31]:
datos #imprimimos el dataset

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,UniqueCarrier,AirlineID,Carrier,TailNum,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2015,1,1,1,4,2015-01-01,AA,19805,AA,N787AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,2,5,2015-01-02,AA,19805,AA,N795AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,3,6,2015-01-03,AA,19805,AA,N788AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,7,2015-01-04,AA,19805,AA,N791AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,5,1,2015-01-05,AA,19805,AA,N783AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,6,2,2015-01-06,AA,19805,AA,N799AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,7,3,2015-01-07,AA,19805,AA,N784AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,8,4,2015-01-08,AA,19805,AA,N787AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,9,5,2015-01-09,AA,19805,AA,N795AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,10,6,2015-01-10,AA,19805,AA,N790AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2015,1,1,11,7,2015-01-11,AA,19805,AA,N786AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2015,1,1,12,1,2015-01-12,AA,19805,AA,N790AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2015,1,1,13,2,2015-01-13,AA,19805,AA,N796AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2015,1,1,14,3,2015-01-14,AA,19805,AA,N793AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2015,1,1,15,4,2015-01-15,AA,19805,AA,N790AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2015,1,1,16,5,2015-01-16,AA,19805,AA,N797AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2015,1,1,17,6,2015-01-17,AA,19805,AA,N795AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2015,1,1,18,7,2015-01-18,AA,19805,AA,N786AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2015,1,1,19,1,2015-01-19,AA,19805,AA,N785AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2015,1,1,20,2,2015-01-20,AA,19805,AA,N797AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,1,1,21,3,2015-01-21,AA,19805,AA,N789AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2015,1,1,22,4,2015-01-22,AA,19805,AA,N790AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2015,1,1,23,5,2015-01-23,AA,19805,AA,N790AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2015,1,1,24,6,2015-01-24,AA,19805,AA,N787AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2015,1,1,25,7,2015-01-25,AA,19805,AA,N791AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2015,1,1,26,1,2015-01-26,AA,19805,AA,N783AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2015,1,1,27,2,2015-01-27,AA,19805,AA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2015,1,1,28,3,2015-01-28,AA,19805,AA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2015,1,1,29,4,2015-01-29,AA,19805,AA,N794AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2015,1,1,30,5,2015-01-30,AA,19805,AA,N792AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469938,2015,1,1,3,6,2015-01-03,NK,20416,NK,N505NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469939,2015,1,1,4,7,2015-01-04,NK,20416,NK,N503NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469940,2015,1,1,5,1,2015-01-05,NK,20416,NK,N508NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469941,2015,1,1,6,2,2015-01-06,NK,20416,NK,N503NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469942,2015,1,1,7,3,2015-01-07,NK,20416,NK,N508NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469943,2015,1,1,8,4,2015-01-08,NK,20416,NK,N503NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469944,2015,1,1,9,5,2015-01-09,NK,20416,NK,N508NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469945,2015,1,1,10,6,2015-01-10,NK,20416,NK,N503NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469946,2015,1,1,11,7,2015-01-11,NK,20416,NK,N508NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469947,2015,1,1,12,1,2015-01-12,NK,20416,NK,N503NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469948,2015,1,1,13,2,2015-01-13,NK,20416,NK,N514NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469949,2015,1,1,14,3,2015-01-14,NK,20416,NK,N528NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469950,2015,1,1,15,4,2015-01-15,NK,20416,NK,N508NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469951,2015,1,1,16,5,2015-01-16,NK,20416,NK,N528NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469952,2015,1,1,17,6,2015-01-17,NK,20416,NK,N508NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469953,2015,1,1,18,7,2015-01-18,NK,20416,NK,N528NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469954,2015,1,1,19,1,2015-01-19,NK,20416,NK,N505NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469955,2015,1,1,20,2,2015-01-20,NK,20416,NK,N521NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469956,2015,1,1,21,3,2015-01-21,NK,20416,NK,N505NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469957,2015,1,1,22,4,2015-01-22,NK,20416,NK,N522NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469958,2015,1,1,23,5,2015-01-23,NK,20416,NK,N502NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469959,2015,1,1,24,6,2015-01-24,NK,20416,NK,N524NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469960,2015,1,1,25,7,2015-01-25,NK,20416,NK,N502NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469961,2015,1,1,26,1,2015-01-26,NK,20416,NK,N524NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469962,2015,1,1,27,2,2015-01-27,NK,20416,NK,N502NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469963,2015,1,1,28,3,2015-01-28,NK,20416,NK,N524NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469964,2015,1,1,29,4,2015-01-29,NK,20416,NK,N502NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469965,2015,1,1,30,5,2015-01-30,NK,20416,NK,N519NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469966,2015,1,1,31,6,2015-01-31,NK,20416,NK,N502NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469967,2015,1,1,1,4,2015-01-01,NK,20416,NK,N502NK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
datos.dropna(how='all')#borramos registros que no tengan datos
print(datos.shape[1])

110

In [33]:
datos.to_csv('resultado_Time_Performance.csv')#se crea archivo csv

In [34]:
#Carrier, FlightNum, Origin, Dest, total de flights por aerolínea y promedio de demoras por aeropuerto.
agrupados = datos[['DepDelay', 'DepDelayMinutes', 'DepartureDelayGroups', 'ArrDelay', 'ArrDelayMinutes'
                  , 'ArrivalDelayGroups', 'CarrierDelay', 'WeatherDelay', 'NASDelay'
                  , 'SecurityDelay', 'LateAircraftDelay', 'OriginAirportID']].groupby('OriginAirportID')
display(agrupados.mean().sort_values('DepDelay', ascending=False)) #agrupamos lo datos para ver el promedio de demora por aeropuerto

,DepDelay,DepDelayMinutes,DepartureDelayGroups,ArrDelay,ArrDelayMinutes,ArrivalDelayGroups,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
OriginAirportID,,,,,,,,,,,
11447,35.627907,40.395349,1.069767,28.871795,32.128205,1.025641,47.692308,0.000000,14.461538,0.000000,27.461538
12519,34.322581,38.419355,1.338710,37.622951,41.147541,1.508197,41.115385,2.807692,8.923077,0.000000,40.153846
12335,32.381818,37.327273,0.672727,12.188679,18.811321,0.245283,41.111111,2.555556,8.666667,0.000000,46.555556
13964,30.375000,33.750000,1.625000,30.000000,32.937500,1.437500,0.166667,0.000000,16.166667,0.000000,64.833333
10930,28.881356,34.406780,1.372881,21.413793,33.034483,0.844828,2.315789,0.000000,57.368421,0.000000,39.578947
15356,26.942982,29.565789,1.105263,22.189427,28.947137,0.859031,25.175000,0.850000,17.162500,0.000000,35.650000
14711,26.492063,29.031746,0.825397,26.793651,33.079365,0.857143,46.818182,3.272727,25.136364,0.000000,15.318182
12320,26.461538,31.884615,1.038462,24.769231,36.653846,1.115385,27.500000,3.200000,34.100000,0.000000,30.300000
10333,25.653061,32.693878,1.000000,21.510204,32.040816,0.775510,11.428571,0.000000,5.714286,0.000000,91.642857
10157,25.088435,29.380952,1.047619,22.239726,29.328767,0.917808,20.687500,0.000000,32.291667,0.000000,33.958333
10728,24.595506,26.550562,1.000000,25.704545,29.045455,0.977273,34.485714,0.000000,6.971429,0.000000,28.885714
10141,24.500000,28.433333,0.166667,23.583333,29.266667,0.083333,140.666667,0.000000,6.555556,0.000000,39.666667
14113,23.633333,30.733333,-0.133333,28.100000,33.966667,0.116667,138.555556,58.888889,10.888889,0.000000,5.222222
11471,22.836066,26.721311,0.557377,24.400000,29.383333,0.616667,63.153846,0.000000,11.384615,0.000000,49.769231
12012,22.095890,27.931507,0.671233,22.328767,30.767123,0.767123,29.071429,0.285714,13.928571,0.000000,34.392857
11587,21.666667,26.666667,0.500000,12.562500,25.208333,-0.062500,118.857143,0.000000,0.000000,0.000000,45.142857
10372,20.867797,24.077966,0.825424,16.988095,23.666667,0.568027,17.318182,1.202020,9.414141,0.681818,38.691919
15380,20.690217,24.081522,0.608696,19.836957,28.597826,0.538043,21.180000,15.940000,23.240000,0.000000,41.540000
14588,20.654321,25.086420,0.580247,27.787500,30.850000,0.962500,9.629630,31.703704,14.629630,0.000000,29.629630
13930,19.962051,21.928696,0.737168,17.016132,23.112027,0.604947,17.726277,12.134054,15.092017,0.011913,22.144735
12441,18.787172,23.081633,0.609329,16.096210,24.379009,0.530612,12.704762,7.476190,20.114286,0.000000,36.371429
15008,18.509091,23.381818,0.581818,20.018519,24.148148,0.648148,10.666667,0.000000,22.066667,0.000000,49.600000
14696,18.491892,22.610811,0.600000,16.326975,25.212534,0.509537,30.666667,12.284314,21.215686,0.000000,23.245098
10627,18.302632,22.398026,0.289474,11.970100,20.262458,0.146179,23.652174,0.000000,20.391304,0.000000,40.637681
11638,18.125547,21.054015,0.386861,17.638235,22.097059,0.427941,36.748634,5.994536,13.841530,0.000000,20.174863
11109,17.912969,21.583618,0.419795,17.541237,24.656357,0.446735,45.291667,18.006944,18.576389,0.000000,12.166667
11503,17.760274,22.609589,0.363014,13.567010,22.233677,0.096220,24.197183,3.845070,12.859155,0.267606,44.098592
10268,17.122449,19.673469,0.673469,20.816327,28.040816,0.897959,13.157895,1.578947,24.315789,0.000000,30.473684
10685,16.418103,19.767241,0.422414,21.740260,26.722944,0.757576,18.800000,2.662500,22.187500,0.000000,29.687500
11003,16.200942,19.704867,0.491366,19.576378,24.825197,0.730709,16.903670,1.431193,20.155963,0.000000,29.706422
...,...,...,...,...,...,...,...,...,...,...,...
12982,1.990576,6.788482,-0.443979,-0.431125,7.308097,-0.505783,19.144144,0.774775,4.729730,1.234234,25.666667
14828,1.793478,8.521739,-0.326087,0.611111,8.011111,-0.422222,0.000000,31.416667,5.500000,0.000000,13.916667
11973,1.621622,6.930931,-0.399399,0.521084,8.192771,-0.442771,12.422222,0.000000,11.422222,0.000000,27.111111
11624,1.584362,7.181070,-0.629630,-0.805785,8.148760,-0.706612,6.055556,0.000000,14.277778,0.000000,78.777778
11617,1.400000,6.927273,-0.436364,-0.690909,8.927273,-0.527273,13.833333,0.000000,14.666667,0.000000,45.833333
10620,1.128440,5.844037,-0.477064,-4.170507,6.912442,-0.737327,4.392857,2.714286,13.857143,0.000000,27.142857
14222,1.100000,2.800000,-0.600000,6.600000,9.000000,0.000000,38.500000,0.000000,0.000000,0.000000,1.000000
10666,1.032258,6.967742,-0.430108,3.311828,10.000000,-0.258065,9.000000,0.000000,15.307692,0.000000,33.615385
10299,1.005111,6.243612,-0.430153,-4.289519,6.049828,-0.712199,18.311927,3.651376,7.018349,0.000000,24.486239
11630,0.896104,7.441558,-0.467532,0.214286,8.935065,-0.519481,11.840000,0.000000,11.400000,0.000000,23.800000
12206,0.888889,5.487455,-0.483871,-2.960289,4.895307,-0.653430,5.708333,4.833333,1.833333,0.000000,35.708333
13061,0.465347,5.762376,-0.430693,0.243781,6.691542,-0.402985,4.370370,0.740741,12.000000,0.000000,22.925926
11252,0.458333,4.108333,-0.600000,-4.126050,4.352941,-0.697479,15.857143,0.000000,27.000000,0.000000,18.000000
13873,0.103448,7.362069,-0.482759,2.344828,8.103448,-0.293103,5.375000,2.750000,0.750000,0.000000,40.875000
12177,0.069767,6.906977,-0.418605,-0.767442,8.279070,-0.488372,0.000000,32.000000,64.333333,0.000000,4.666667
11041,-0.405000,3.980000,-0.575000,0.130000,5.925000,-0.465000,0.458333,2.250000,15.083333,0.000000,20.666667
12156,-0.682243,3.018692,-0.551402,-6.792453,4.990566,-0.877358,0.000000,5.307692,17.846154,0.000000,10.076923
10739,-1.576923,5.596154,-0.615385,5.134615,10.596154,-0.192308,0.000000,0.000000,17.500000,1.500000,27.200000
10918,-2.056604,5.867925,-0.547170,-4.018868,6.886792,-0.698113,1.250000,0.000000,8.625000,0.000000,32.125000
14254,-2.069444,6.458333,-0.611111,-2.652778,7.847222,-0.680556,11.714286,0.000000,12.000000,0.000000,42.857143
10551,-2.312500,5.837500,-0.600000,-0.787500,6.687500,-0.525000,1.285714,14.000000,9.000000,3.000000,40.857143
15389,-5.517857,1.303571,-0.875000,-5.660714,1.946429,-0.857143,0.000000,14.000000,5.000000,0.000000,10.500000
13127,-6.358491,0.301887,-0.924528,-10.660377,0.622642,-1.226415,0.000000,0.000000,3.000000,0.000000,14.000000
10165,-6.666667,4.333333,-0.777778,-3.000000,7.000000,-0.666667,0.000000,0.000000,11.500000,15.500000,0.000000
10779,-7.152542,0.694915,-0.983051,-14.050847,0.406780,-1.338983,NaN,NaN,NaN,NaN,NaN
15991,-8.016949,6.254237,-0.898305,-12.689655,6.275862,-1.034483,0.000000,4.714286,3.285714,0.000000,43.428571
10926,-8.333333,6.116667,-1.016667,-8.694915,6.491525,-0.932203,0.000000,0.000000,2.625000,0.000000,43.375000
10170,-8.827586,3.689655,-1.034483,-7.310345,4.275862,-0.931034,0.000000,0.000000,6.000000,0.000000,42.500000
11525,-8.852459,0.786885,-1.081967,-4.950820,3.590164,-0.704918,16.000000,0.000000,25.500000,0.000000,5.000000
11092,-8.888889,0.333333,-1.018519,-26.092593,0.166667,-1.907407,NaN,NaN,NaN,NaN,NaN

In [35]:
#Obtener nombre de máquinas y aerolíneas respectivamente propensas a descomponerse y demorarse.
dems = datos[(datos['ArrDelay'] >0) | (datos['DepDelay'] >0) | (datos['CarrierDelay'] >0) 
           | (datos['WeatherDelay'] >0) | (datos['NASDelay'] >0) | (datos['SecurityDelay'] >0)
           | (datos['LateAircraftDelay'] >0)]
demoras = pd.Series.value_counts(dems['AirlineID']).to_dict()

In [36]:
totales = pd.Series.value_counts(datos['AirlineID']).to_dict()

In [39]:
for key in demoras:#for para ver el promedio de demoras por aerolinea
    print(str(key) + ": " + str(demoras[key]/totales[key]))

19393: 0.508856280362
19790: 0.393427609009
20304: 0.491520139668
20366: 0.467581372058
19977: 0.593618960802
19805: 0.498604144443
20398: 0.543043478261
20355: 0.455313685091
20409: 0.482911714378
19930: 0.414196273667
20416: 0.55541576118
20436: 0.573436813589
19690: 0.464751552795
21171: 0.466708941027

In [ ]:
#La aerolinea con mayor tendencia al retraso es la 19977